export type Product = {
  id: number
  name: string
  category: string
  price: number
  originalPrice?: number
  rating: number
  reviews: number
  image: string
  badge?: string
  inStock: boolean
}

export const products: Product[] = [
  // Cleaning
  {
    id: 1,
    name: 'Heavy Duty Floor Cleaner',
    category: 'Cleaning',
    price: 299,
    originalPrice: 399,
    rating: 4.8,
    reviews: 1240,
    image: '/service-cleaning.jpg',
    badge: 'Best Seller',
    inStock: true,
  },
  {
    id: 2,
    name: 'Multi-Surface Spray',
    category: 'Cleaning',
    price: 149,
    originalPrice: 199,
    rating: 4.6,
    reviews: 870,
    image: '/service-cleaning.jpg',
    inStock: true,
  },
  {
    id: 3,
    name: 'Microfiber Mop Set',
    category: 'Cleaning',
    price: 549,
    originalPrice: 699,
    rating: 4.7,
    reviews: 640,
    image: '/service-cleaning.jpg',
    badge: 'New',
    inStock: true,
  },
  // Appliances
  {
    id: 4,
    name: 'Pressure Washer 1800W',
    category: 'Appliances',
    price: 4999,
    originalPrice: 6499,
    rating: 4.5,
    reviews: 320,
    image: '/service-appliance.jpg',
    badge: '23% Off',
    inStock: true,
  },
  {
    id: 5,
    name: 'Steam Cleaning Machine',
    category: 'Appliances',
    price: 3499,
    rating: 4.4,
    reviews: 215,
    image: '/service-appliance.jpg',
    inStock: true,
  },
  {
    id: 6,
    name: 'Cordless Vacuum Cleaner',
    category: 'Appliances',
    price: 6999,
    originalPrice: 8999,
    rating: 4.9,
    reviews: 1850,
    image: '/service-appliance.jpg',
    badge: 'Top Rated',
    inStock: true,
  },
  // Tools
  {
    id: 7,
    name: 'Professional Drill Set',
    category: 'Tools',
    price: 1899,
    originalPrice: 2499,
    rating: 4.7,
    reviews: 560,
    image: '/service-appliance.jpg',
    inStock: true,
  },
  {
    id: 8,
    name: 'Wrench Combo Kit',
    category: 'Tools',
    price: 799,
    rating: 4.5,
    reviews: 430,
    image: '/service-appliance.jpg',
    inStock: true,
  },
  // Home Care
  {
    id: 9,
    name: 'Paint Roller Set',
    category: 'Home Care',
    price: 349,
    originalPrice: 499,
    rating: 4.6,
    reviews: 720,
    image: '/service-painting.jpg',
    inStock: true,
  },
  {
    id: 10,
    name: 'Waterproof Sealant',
    category: 'Home Care',
    price: 249,
    rating: 4.3,
    reviews: 310,
    image: '/service-painting.jpg',
    badge: 'New',
    inStock: true,
  },
  {
    id: 11,
    name: 'Wall Putty 5kg',
    category: 'Home Care',
    price: 199,
    originalPrice: 249,
    rating: 4.5,
    reviews: 580,
    image: '/service-painting.jpg',
    inStock: true,
  },
  // Safety
  {
    id: 12,
    name: 'Smoke Detector (Pack of 2)',
    category: 'Safety',
    price: 699,
    rating: 4.8,
    reviews: 940,
    image: '/service-electrical.jpg',
    badge: 'Best Seller',
    inStock: true,
  },
  {
    id: 13,
    name: 'Fire Extinguisher 1kg',
    category: 'Safety',
    price: 899,
    originalPrice: 1099,
    rating: 4.7,
    reviews: 670,
    image: '/service-electrical.jpg',
    inStock: true,
  },
  {
    id: 14,
    name: 'Safety Gloves Set',
    category: 'Safety',
    price: 299,
    rating: 4.4,
    reviews: 280,
    image: '/service-electrical.jpg',
    inStock: true,
  },
  // Plumbing
  {
    id: 15,
    name: 'Pipe Repair Kit',
    category: 'Plumbing',
    price: 449,
    originalPrice: 599,
    rating: 4.6,
    reviews: 390,
    image: '/service-plumbing.jpg',
    inStock: true,
  },
  {
    id: 16,
    name: 'Drain Cleaning Brush Set',
    category: 'Plumbing',
    price: 199,
    rating: 4.3,
    reviews: 240,
    image: '/service-plumbing.jpg',
    badge: 'New',
    inStock: true,
  },
  {
    id: 17,
    name: 'Plumbers Tape (Pack of 5)',
    category: 'Plumbing',
    price: 99,
    originalPrice: 149,
    rating: 4.5,
    reviews: 810,
    image: '/service-plumbing.jpg',
    inStock: true,
  },
]
